version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbit
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - hogwarts
  potter:
    build: ./potter
    ports:
      - 8080:8080
    container_name: potter
    networks:
      - hogwarts
networks:
  hogwarts:
    driver: bridge
