version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbit
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - hogwarts
  hermione:
    build: ./hermione
    ports:
      - 8080:8080
    container_name: hermione
    networks:
      - hogwarts
  hagrid:
    build:
      context: ./hagrid
      dockerfile: ./Dockerfile
    ports:
      - 9090:9090
    container_name: hagrid
    networks:
      - hogwarts
networks:
  hogwarts:
    driver: bridge
