version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbit
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - hogwarts
  hermione:
    build: ./hermione
    ports:
      - 8080:8080
    container_name: hermione
    networks:
      - hogwarts
  hagrid:
    build:
      context: ./hagrid
      dockerfile: ./Dockerfile
    ports:
      - 9090:9090
    container_name: hagrid
    networks:
      - hogwarts
  dumbledore:
    build:
      context: ./dumbledore
      dockerfile: ./Dockerfile
    ports:
      - 9091:9091
    container_name: dumbledore
    networks:
      - hogwarts
  filtch:
    build:
      context: ./filtch
      dockerfile: ./Dockerfile
    ports:
      - 9092:9092
    container_name: filtch
    networks:
      - hogwarts
  mongo:
    image: mongo
    hostname: ron
    container_name: ron
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - hogwarts
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    networks:
      - hogwarts
networks:
  hogwarts:
    driver: bridge
