apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expiry-ingress
 #annotations:
  # kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: expiry.ddns.net
    http:
      paths:
      - path: /filtch
        pathType: Prefix
        backend:
          service:
            name: filtch
            port:
              number: 80
      - path: /dumbledore
        pathType: Prefix
        backend:
          service:
            name: dumbledore
            port:
              number: 80
