apiVersion: apps/v1
kind: Deployment
metadata:
  name: filtch
  labels:
    app: filtch
spec:
  selector:
    matchLabels:
      app: filtch
  replicas: 1
  template:
    metadata:
      labels:
        app: filtch
    spec:
      containers:
      - name: filtch
        image: filtch:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: filtch-secret
              key: mongo_user
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: filtch-secret
              key: mongo_password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: filtch-secret
              key: jwt_secret
        - name: MONGO_HOST
          valueFrom:
            configMapKeyRef:
              name: filtch-configmap
              key: mongo_host
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: filtch-configmap
              key: mongo_port
        - name: MONGO_DB
          valueFrom:
            configMapKeyRef:
              name: filtch-configmap
              key: mongo_database
        - name: MONGO_AUTH_DB
          valueFrom:
            configMapKeyRef:
              name: filtch-configmap
              key: mongo_auth_database
---
apiVersion: v1
kind: Service
metadata:
  name: filtch
  labels:
    name: filtch
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  clusterIP: None
  selector:
    app: filtch
